title: "Kristina Aggas â€“ Data Analysis Projects"
description: "Portfolio of SAS, R, Python, SQL, and data analysis work."

remote_theme: pages-themes/modernist@v0.2.0

plugins:
  - jekyll-remote-theme
